#
# Shared Makefile to add as a stub/proxy to redirect the user to 
# using "just" rather than Make.
#

.PHONY: default
default:
	@which just > /dev/null || cargo install just
	@echo
	@echo "Use 'just <recipe>' to run commands"
	@echo
	@just

*: default
