[workspace]
members = [
    # Commands
    "source/cmd/snowglobe",
    "source/cmd/snowtale",
    # Crates
    "source/crates/snowfall_bevy",
    "source/crates/snowfall_core",
    "source/crates/snowfall_voxel",
    # Tools
    "source/tools/voxel_viewer",
]
