# Unfortunately environment variables don't seem to support in the import path
import "../../common/webapp.justfile"


###############################################################################
# Core commands
###############################################################################

_default: _common-default

# idempotent installation of dependencies & configuration
ensure: _common-ensure-webapp
    #!/usr/bin/env bash
    TARGET=./src/snowfall-core
    SOURCE=$MONOREPO_ROOT/source/lib/snowfall-core/src
    if [ ! -L $TARGET ] && [ -e $SOURCE ]; then
        ln -s $SOURCE $TARGET
    fi

build: ensure
    just _common-build-bundle ./src/main.tsx ./dist/main.bundle.js
    cp -f ./src/index.html ./dist/index.html

dev:
    mprocs \
        --names "client,server" \
        "just _common-dev-watch ./src 'just build'" \
        "just run"

run: build
    npx serve ./dist



