# Unfortunately environment variables don't seem to support in the import path
import "../../common/webapp.justfile"


###############################################################################
# Core commands
###############################################################################

_default: _common-default

# idempotent installation of dependencies & configuration
ensure: _common-ensure-webapp
    @just _link-src-lib raiment-core
    @just _link-src-lib raiment-ui

build: ensure
    just _common-build-bundle ./src/main.tsx ./dist/main.bundle.js
    cp -f ./src/index.html ./dist/index.html

dev:
    mprocs \
        --names "client,server" \
        "just _common-dev-watch ./src 'just build'" \
        "just run"

run: build
    npx serve ./dist -p 8080

