[package]
name = "model_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
snowfall_voxel = { path = "../../crates/snowfall_voxel" }
snowfall_core = { path = "../../crates/snowfall_core" }
