name: CI
on:
    push:
        branches:
            - main
    pull_request:
env:
    CARGO_TERM_COLOR: always
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
            - name: Install dependencies
              run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Run tests
              run: cargo test --all
